var gridded = ["Andhra Pradesh", "Odisha", "Arunachal Pradesh",
	"Gujarat", "Chattisgarh", "Punjab", "Nagaland", "Rajasthan",
	"Maharashtra", "Telangana", "Haryana", "Bihar", "Jharkhand",
	"Kerala", "Karnataka", "Assam", "Madhya Pradesh", "Tamilnadu",
	"Lakshadweep", "Uttar Pradesh", "Mizoram", "Jammu & Kashmir",
	"West Bengal", "Uttarakhand", "Tripura", "Himachal Pradesh",
	"Meghalaya", "Puducherry", "Goa", "Manipur",
	"Andaman & Nicobar", "Delhi", "Chandigarh", "Sikkim",
	"Dadar & Nagar Haveli", "Daman & Diu", "Ladakh"]

var actual=["A & N ISLAND","ARUNACHAL PRADESH","ASSAM","MEGHALAYA","HARYANA",
	"NAGALAND","MANIPUR","MIZORAM","TRIPURA","SIKKIM","WEST BENGAL","ODISHA","JHARKHAND",
	"BIHAR","UTTAR PRADESH","UTTARAKHAND","CHANDIGARH (UT)","DELHI (UT)","PUNJAB","HIMACHAL PRADESH","JAMMU & KASHMIR (UT)","LADAKH (UT)","RAJASTHAN","MADHYA PRADESH","GUJARAT","DADAR & NAGAR HAVELI (UT)","DAMAN & DIU (UT)","GOA","MAHARASHTRA","CHHATTISGARH","COASTAL AP and YANAM","ANDHRA PRADESH","TAMIL NADU","PUDUCHERRY (UT)","KARNATAKA","KERALA & MAHE","LAKSHADWEEP"] ;

/*
 * var actual = ["SUBDIVISION : A & N ISLAND", "NICOBAR", "NORTH & MIDDLE
 * ANDAMAN", "SOUTH ANDAMAN", "SUBDIVISION : ARUNACHAL PRADESH", "ANJAW",
 * "CHANGLANG", "DIBANG VALLEY", "EAST KAMENG", "EAST SIANG", "KURUNG KUMEY",
 * "LOHIT", "LOWER DIBANG VALLEY", "LOWER SUBANSIRI", "PAPUM-PARE", "TAWANG",
 * "TIRAP", "UPPER SIANG", "UPPER SUBANSIRI", "WEST KAMENG", "WEST SIANG",
 * "SUBDIVISION : ASSAM & MEGHALAYA", "STATE : ASSAM", "BAKSA", "BARPETA",
 * "BONGAIGAON", "CACHAR", "CHIRANG", "DARRANG", "DHEMAJI", "DHUBRI",
 * "DIBRUGARH", "GOALPARA", "GOLAGHAT", "HAILAKANDI", "JORHAT", "KAMRUP METRO",
 * "KAMRUP RURAL", "KARBI ANALOG", "KARIMGANJ", "KOKRAJHAR", "LAKHIMPUR",
 * "MORIGAON", "N.C HILLS", "NAGAON", "NALBARI", "SIBSAGAR", "SONITPUR",
 * "TINSUKIA", "UDALGURI", "STATE : MEGHALAYA", "EAST GARO HILLS", "EAST KHASI
 * HILLS", "JAINTIA HILLS", "RI BHOI", "SOUTH GARO HILLS", "WEST GARO HILLS",
 * "WEST KHASI HILLS", "SUBDIVISION : N M M T", "STATE : NAGALAND", "DIMAPUR",
 * "KIPHIRE", "KOHIMA", "LONGLENG", "MOKOKCHUNG", "MON", "PEREN", "PHEK",
 * "TUENSANG", "WOKHA", "ZUNHEBOTO", "STATE : MANIPUR", "BISHNUPUR", "CHANDEL",
 * "CHURACHANDPUR", "IMPHAL EAST", "IMPHAL WEST", "SENAPATI", "TAMENGLONG",
 * "THOUBAL", "UKHRUL", "STATE : MIZORAM", "AIZAWL", "CHAMPHAI", "KOLASIB",
 * "LAWNGTLAI", "LUNGLEI", "MAMIT", "SAIHA", "SERCHHIP", "STATE : TRIPURA",
 * "DHALAI", "NORTH TRIPURA", "SOUTH TRIPURA", "WEST TRIPURA", "SUBDIVISION :
 * SHWB & SIKKIM", "STATE : SIKKIM", "EAST SIKKIM", "NORTH SIKKIM", "SOUTH
 * SIKKIM", "WEST SIKKIM", "STATE : WEST BENGAL", "DAKSHIN DINAJPUR",
 * "DARJEELING", "JALPAIGURI", "KOCHBIHAR", "MALDA", "UTTAR_DINAJPUR",
 * "SUBDIVISION : GANGETIC WEST BENGAL", "BANKURA", "BARDAMAN", "BIRBHUM",
 * "EASTMEDNIPUR", "HAORA", "HUGLI", "KOLKATA", "MURSIDABAD", "NADIA", "NORTH 24
 * PRAGANA", "PASHCHIM MEDINIPUR", "PURULIYA", "SOUTH 24 PARGANAS", "SUBDIVISION :
 * ODISHA", "ANUGUL", "BALANGIR", "BALESHWAR", "BARAGARH", "BAUDA", "BHADRAK",
 * "CUTTACK", "DEOGARH", "DHENKANAL", "GAJAPATHI", "GANJAM", "JAGATSINGHAPUR",
 * "JAJAPUR", "JHARSUGUDA", "KALAHANDI", "KANDHAMAL", "KENDRAPARHA",
 * "KENDUJHAR", "KHORDHA", "KORAPUT", "MALKANGIRI", "MAYURBHANJ",
 * "NABARANGAPUR", "NAYAGARH", "NUAPARHA", "PURI", "RAYAGARHA", "SAMBALPUR",
 * "SUBARNAPUR", "SUNDARGARH", "SUBDIVISION : JHARKHAND", "BOKARO", "CHATRA",
 * "DEOGHAR", "DHANBAD", "DUMKA", "EAST SINGHBHUM", "GARHWA", "GIRIDIH",
 * "GODDA", "GUMLA", "HAZARIBAGH", "JAMTARA", "KHUNTI", "KODERMA", "LATEHAR",
 * "LOHARDAGA", "PAKUR", "PALAMU", "RAMGARH", "RANCHI", "SAHEBGANJ",
 * "SARAIKELA", "SIMDEGA", "WEST SINGHBHUM", "SUBDIVISION : BIHAR", "ARARIYA",
 * "ARWAL", "AURANGABAD", "BANKA", "BEGUSARAI", "BHABUA", "BHAGALPUR",
 * "BHOJPUR", "BUXAR", "DRABHANGA", "GAYA", "GOPALGANJ", "JAHANABAD", "JAMUI",
 * "KATIHAR", "KHAGARIA", "KISHANGANJ", "LAKHISARAI", "MADHEPURA", "MADUBANI",
 * "MUNGER", "MUZAFFARPUR", "NALANDA", "NAWADA", "PACHIM CHAMPARAN", "PATNA",
 * "PURBA CHAMPARAN", "PURNIA", "ROHTAS", "SAHARSA", "SAMASTIPUR", "SARAN",
 * "SHEIKHPURA", "SHEOHAR", "SITAMARHI", "SIWAN", "SUPAUL", "VAISHALI",
 * "SUBDIVISION : EAST UTTAR PRADESH", "STATE : UTTAR PRADESH", "ALLAHABAD",
 * "AMBEDKARNAGAR", "AMETHI", "AZAMGARH", "BAHRAICH", "BALLIA", "BALRAMPUR",
 * "BANDA", "BARABANKI", "BASTI", "CHANDAULI", "CHITRAKOOT", "DEORIA",
 * "FAIZABAD", "FARRUKHABAD", "FATEHPUR", "GAZIPUR", "GONDA", "GORAKHPUR",
 * "HARDOI", "JAUNPUR", "KANNAUJ", "KANPUR", "KANPUR DEHAT", "KAUSHAMBI",
 * "KHERI", "KUSHINAGAR", "LUCKNOW", "MAHARAJGANJ", "MAU", "MIRZAPUR",
 * "PRATAPGARH", "RAIBEARELI", "SANTKABIRNAGAR", "SANTRAVIDASNAGAR",
 * "SHRAWASTI", "SIDDHARTHNAGAR", "SITAPUR", "SONBHADRA", "SULTANPUR", "UNNAO",
 * "VARANASI", "SUBDIVISION : WEST UTTAR PRADESH", "AGRA", "ALIGARH", "AURAIYA",
 * "BADAUN", "BAGHPAT", "BAREILLY", "BIJNOR", "BULANDSAHAR", "ETAH", "ETAWAH",
 * "FIROZABAD", "GAUTAMBUDHNAGAR", "GHAZIABAD", "HAMIRPUR", "HAPUR", "JALAUN",
 * "JHANSI", "JYOTIBAPHULE NAGAR", "KANSHIRAMNAGAR", "LALITPUR",
 * "MAHAMAYANAGAR", "MAHOBA", "MAINPURI", "MATHURA", "MEERUT", "MORADABAD",
 * "MUZAFARNAGAR", "PILHIBHIT", "RAMPUR", "SAMBHAL", "SHAHJAHANPUR", "SHAMLI",
 * "SHARANPUR", "SUBDIVISION : UTTARAKHAND", "ALMORA", "BAGESHWAR", "CHAMOLI",
 * "CHAMPAWAT", "DEHRADUN", "HARIDWAR", "NANITAL", "PAURI GARHWAL",
 * "PITHORAGARH", "RUDRAPRAYAG", "TEHRI GARWAL", "UDHAM SINGH NAGAR",
 * "UTTARKASHI", "SUBDIVISION : HAR. CHD & DELHI", "STATE : HARYANA", "AMBALA",
 * "BHIWANI", "FARIDABAD", "FATEHABAD", "GURGAON", "HISAR", "JHAJJAR", "JIND",
 * "KAITHAL", "KARNAL", "KURUKSHETRA", "MAHENDRAGARH", "MEWAT", "PALWAL",
 * "PANCHKULA", "PANIPAT", "REWARI", "ROHTAK", "SIRSA", "SONIPAT",
 * "YAMUNANAGAR", "STATE : CHANDIGARH (UT)", "CHANDIGARH", "STATE : DELHI (UT)",
 * "CENTRAL DELHI", "EAST DELHI", "NEW DELHI", "NORTH DELHI", "NORTH EAST
 * DELHI", "NORTH WEST DELHI", "SOUTH DELHI", "SOUTH WEST DELHI", "WEST DELHI",
 * "SUBDIVISION : PUNJAB", "AMRITSAR", "BARNALA", "BATHINDA", "FARIDKOT",
 * "FATEHGARH SAHIB", "FIROZPUR", "GURDASPUR", "HOSHIARPUR", "JALANDHAR",
 * "KAPURTHALA", "LUDHIANA", "MANSA", "MOGA", "MUKTSAR", "NAWASHAHR", "PATIALA",
 * "RUPNAGAR", "SANGRUR", "SAS NAGAR", "TARN TARAN", "SUBDIVISION : HIMACHAL
 * PRADESH", "BILASPUR", "CHAMBA", "KANGRA", "KINNAUR", "KULLU", "LAHUL&SPITI",
 * "MANDI", "SHIMLA", "SIRMAUR", "SOLAN", "UNA", "SUBDIVISION : JAMMU & KASHMIR
 * AND LADAKH", "STATE : JAMMU & KASHMIR (UT)", "ANANTNAG", "BADGAM",
 * "BANDIPORE", "BARAMULA", "DODA", "GANDERWAL", "JAMMU", "KATHUA", "KISTWAR",
 * "KULGAM", "KUPWARA", "PULWAMA", "PUNCH", "RAJOURI", "RAMBAN", "RIASI",
 * "SAMBA", "SHOPIAN", "SRINAGAR", "UDHAMPUR", "STATE : LADAKH (UT)", "KARGIL",
 * "LEH AND LADAKH", "SUBDIVISION : WEST RAJASTHAN", "STATE : RAJASTHAN",
 * "BARMER", "BIKANER", "CHURU", "GANGANAGAR", "HANUMANGARH", "JAISELMER",
 * "JALOR", "JODHPUR", "NAGAUR", "PALI", "SUBDIVISION : EAST RAJASTHAN",
 * "AJMER", "ALWAR", "BANSWARA", "BARAN", "BHARATPUR", "BHILWARA", "BUNDI",
 * "CHITTAURGARH", "DAUSA", "DHOLPUR", "DUNGARPUR", "JAIPUR", "JHALAWAR",
 * "JHUNJHUNUN", "KARAULI", "KOTA", "RAJSMAND", "SIKAR", "SIROHI",
 * "SWAIMADHOPUR", "TONK", "UDAIPUR", "SUBDIVISION : WEST MADHYA PRADESH",
 * "STATE : MADHYA PRADESH", "AGAR-MALWA", "ALIRAJPUR", "ASHOKNAGAR", "BARWANI",
 * "BETUL", "BHIND", "BHOPAL", "BURHANPUR", "DATIA", "DEWAS", "DHAR", "GUNA",
 * "GWALIOR", "HARDA", "HOSHANGABAD", "INDORE", "JHABUA", "KHANDWA", "KHARGONE",
 * "MANDSAUR", "MORENA", "NIMACH", "RAISEN", "RAJGARH", "RATLAM", "SEHORE",
 * "SHAJAPUR", "SHEOPUR", "SHIVPURI", "UJJAIN", "VIDESHA", "SUBDIVISION : EAST
 * MADHYA PRADESH", "ANUPPUR", "BALAGHAT", "CHHATARPUR", "CHHINDWARA", "DAMOH",
 * "DINDORI", "JABALPUR", "KATNI", "MANDLA", "NARSHIMAPURA", "PANNA", "REWA",
 * "SAGAR", "SATNA", "SEONI", "SHAHDOL", "SIDHI", "SINGRAULI", "TIKAMGARH",
 * "UMARIA", "SUBDIVISION : GUJARAT REGION", "DAMAN", "STATE : GUJARAT",
 * "AHMADABAD", "ANAND", "ARAVALLI", "BANASKANTHA", "BHARUCH", "CHHOTA UDEPUR",
 * "DAHOD", "DANGS", "GANDHINAGAR", "KHERA", "MAHESANA", "MAHISAGAR", "NARMADA",
 * "NAVSARI", "PANCHMAHAL", "PATAN", "SABAR KANTHA", "SURAT", "TAPI",
 * "VADODARA", "VALSAD", "STATE : DADAR & NAGAR HAVELI (UT)", "DADAR & NAGAR
 * HAVELI", "SUBDIVISION : SAURASHTRA & KUTCH", "AMRELI", "BHAVNAGAR", "BOTAD",
 * "DEVBHOOMI DWARKA", "GIR SOMNATH", "JAMNAGAR", "JUNAGARH", "KACHCHH",
 * "MORBI", "PORBANDAR", "RAJKOT", "SURENDRANAGAR", "DIU", "STATE : DAMAN & DIU
 * (UT)", "SUBDIVISION : KONKAN & GOA", "STATE : GOA", "NORTH GOA", "SOUTH GOA",
 * "STATE : MAHARASHTRA", "MUMBAI CITY", "PALGHAR", "RAIGARH", "RATNAGIRI",
 * "SINDHUDURG", "SUBURBAN MUMBAI", "THANE", "SUBDIVISION : MADHYA MAHARASHTRA",
 * "AHMADNAGAR", "DHULE", "JALGAON", "KOLHAPUR", "NANDURBAR", "NASIK", "PUNE",
 * "SANGLI", "SATARA", "SOLAPUR", "SUBDIVISION : MARATHWADA", "BID", "HINGOLI",
 * "JALNA", "LATUR", "NANDED", "OSMANABAD", "PARBHANI", "SUBDIVISION :
 * VIDARBHA", "AKOLA", "AMARAVATI", "BHANDARA", "BULDHANA", "CHANDRAPUR",
 * "GADCHIROLI", "GONDIYA", "NAGPUR", "WARDHA", "WASHIM", "YAVATMAL",
 * "SUBDIVISION : CHHATTISGARH", "BALARAMPUR", "BALOD", "BALODA BAZAR",
 * "BASTAR", "BEMETARA", "BIJAPUR", "DANTEWARA", "DHAMTARI", "DURG",
 * "GARIABAND", "JANJGIR_CHAMPA", "JASHPUR", "KABIRDHAM", "KANKER", "KONDAGAON",
 * "KORBA", "KOREA", "MAHASAMUND", "MUNGELI", "NARAYANPUR", "RAIPUR",
 * "RAJNANDGAON", "SUKMA", "SURAJPUR", "SURGUJA", "SUBDIVISION : COASTAL AP and
 * YANAM", "YANAM", "STATE : ANDHRA PRADESH", "EAST GODAVARI", "GUNTUR",
 * "KRISHNA", "NELLORE", "PRAKASAM", "SRIKAKULAM", "VISHAKHAPATNAM",
 * "VIZIANAGARAM", "WEST GODAVARI", "SUBDIVISION : TELANGANA", "ADILABAD", "B.
 * KOTHAGUDEM", "HYDERABAD", "J. BHUPALPALLY", "JAGTIAL", "JANGAON", "JOGULAMBA
 * GADWAL", "KAMAREDDY", "KARIMNAGAR", "KHAMMAM", "KUMARAM BHEEM", "M.
 * MALKAJGIRI", "MAHABUBABAD", "MAHABUBNAGAR", "MANCHERIAL", "MEDAK", "MULUGU",
 * "NAGARKURNOOL", "NALGONDA", "NARAYANPET", "NIRMAL", "NIZAMABAD",
 * "PEDDAPALLE", "RAJANNA SIRCILLA", "RANGAREDDY", "SANGAREDDY", "SIDDIPET",
 * "SURYAPET", "VIKARABAD", "WANAPARTHY", "WARANGAL_RURAL", "WARANGAL_URBAN",
 * "Y. BHUVANAGIRI", "SUBDIVISION : RAYALASEEMA", "ANANTHAPUR", "CHITTOOR",
 * "CUDDAPAH", "KURNOOL", "SUBDIVISION : TN PUDU and KARAIKAL", "STATE : TAMIL
 * NADU", "ARIYALUR", "CHENGALPATTU", "CHENNAI", "COIMBATORE", "CUDDALORE",
 * "DHARAMPURI", "DINDIGUL", "ERODE", "KALLAKURICHI", "KANCHIPURAM",
 * "KANYAKUMARI", "KARUR", "KRISHNAGIRI", "MADURAI", "NAGAPATTINAM", "NAMAKKAL",
 * "NILGIRI", "PERAMBALUR", "PUDUKKOTTAI", "RAMANATHAPURAM", "RANIPET", "SALEM",
 * "SIVAGANGA", "TENI", "TENKASI", "THANJAVUR", "THIRUVARUR", "TIRUCHIRAPPALLI",
 * "TIRUNELVELI", "TIRUPATTUR", "TIRUPPUR", "TIRUVALLUR", "TIRUVANNAMALAI",
 * "TUTICORIN", "VELLORE", "VILLUPURAM", "VIRUDHUNAGAR", "STATE : PUDUCHERRY
 * (UT)", "KARAIKAL", "MAHE", "PUDUCHERY", "SUBDIVISION : COASTAL KARNATAKA",
 * "STATE : KARNATAKA", "DAKSHIN KANNADA", "UDUPI", "UTTAR KANNADA",
 * "SUBDIVISION : N. I. KARNATAKA", "BAGALKOT", "BELGAUM", "BIDAR", "DHARWAD",
 * "GADAG", "GULBARGA", "HAVERI", "KOPPAL", "RAICHUR", "YADGIR", "SUBDIVISION :
 * S. I. KARNATAKA", "BANGALORE RURAL", "BANGLORE URBAN", "BELLARY",
 * "CHAMARAJANAGAR", "CHIKBALLAPUR", "CHIKMAGALUR", "CHITRADURGA", "DAVANGERE",
 * "HASSAN", "KODAGU", "KOLAR", "MANDHYA", "MYSORE", "RAMNAGAR", "SHIMOGA",
 * "TUMKUR", "SUBDIVISION : KERALA & MAHE", "ALAPPUZHA", "ERNAKULAM", "IDUKKI",
 * "KANNUR", "KASARGOD", "KOLLAM", "KOTTYAM", "KOZIKOD", "MALAPPURAM",
 * "PALAKKAD", "PATTANAMITTIA", "THIRUVANANTHPURAM", "TRISHUR", "WAYANAD",
 * "SUBDIVISION : LAKSHADWEEP", "LAKSHADWEEP"]
 */

function createOption(element, val) {
	var option = document.createElement("option");
	option.text = val;
	option.value = val;
	element.appendChild(option);
}

function statusChangeListener(event) {
	var state1 = document.getElementById("State");
	switch (event.target.value) {

		case "Actual District":
			state1.innerHTML = "";
			createOption(state1, "--Select--");
			actual.forEach(val => {
				createOption(state1, val);
			})

			break;
		case "Block Grided":
			state1.innerHTML = "";
			createOption(state1, "--Select--");
			gridded.forEach(val => {
				createOption(state1, val);
			})
			break;
		case "Min Temperature":
			state1.innerHTML = "";
			createOption(state1, "--Select--");
			gridded.forEach(val => {
				createOption(state1, val);
			})
			break;
		case "Max Temperature":
			state1.innerHTML = "";
			createOption(state1, "--Select--");
			gridded.forEach(val => {
				createOption(state1, val);
			})
			break;
		case "select":
			state1.innerHTML = "";
			createOption(state1, "select");
	}
}


function DateValidation() {
	var startDate = document.getElementById("fdate").value;
	var endDate = document.getElementById("tdate").value;

	if ((Date.parse(startDate) >= Date.parse(endDate))) {
		swal({
				title : "Oops...",
				text : "End date should be greater than start date",
				icon : "error",
				timer : "200000",
				Button : "Close",
				closeModal : "true",
			})
		document.getElementById("tdate").value = "";
	}
	





}